name: tvOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        xcodebuild -scheme Neron \
        -destination generic/platform=tvOS
      
      
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        xcodebuild -scheme Neron \
        -destination generic/platform=tvOS \
        test
