line_length:
    warning: 180
    error: 240
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 700
    error: 1200
    ignore_comment_only_lines: true

opt_in_rules:
- anyobject_protocol
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- convenience_type
- discouraged_object_literal
- empty_count
- empty_string
- explicit_init
- fallthrough
- first_where
- force_unwrapping
- function_default_parameter_at_end
- identical_operands
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- no_extension_access_modifier
- number_separator
- operator_usage_whitespace
- override_in_extension
- overridden_super_call
- pattern_matching_keywords
- private_action
- private_outlet
- private_over_fileprivate
- prohibited_super_call
- redundant_nil_coalescing
- single_test_class
- sorted_first_last
- sorted_imports
- todo
- toggle_bool
- unneeded_parentheses_in_closure_argument
- yoda_condition

disabled_rules:
- nesting
- cyclomatic_complexity
- type_name
- weak_delegate
- identifier_name
- trailing_whitespace
- unavailable_function
- discouraged_optional_boolean
- discouraged_optional_collection
