name: iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -showdestinations -scheme Neron
      
      
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: xcodebuild -showdestinations -scheme NeronTests
