name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
      
jobs:
    tests:
        runs-on: macos-latest
        name: Test ${{ matrix.platform }}
        strategy:
          fail-fast: false
          matrix:
            platform: [macOS, iOS, tvOS]
            include:
                - platform: macOS
                  destination: platform=OS X,arch=x86_64
                - platform: iOS
                  destination: platform=iOS Simulator,name=iPhone 11,OS=latest
                - platform: tvOS
                  destination: platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=latest
        steps:
          - name: Setup xcode version
            uses: maxim-lobanov/setup-xcode@v1.6.0
            with:
                xcode-version: latest-stable
          - name: Checkout
            uses: actions/checkout@v4
          - name: Run ${{ matrix.platform }} tests
            run: |
                xcodebuild -scheme Neron \
                -destination '${{ matrix.destination }}' \
                test
